=== Rouji/raymond/scenes/scene.dtd
<!ELEMENT scene (background_color, camera, lights, surfaces)>
<!ELEMENT background_color EMPTY>

<!ELEMENT camera (position, lookat, up, horizontal_fov, resolution, max_bounces)>
<!ELEMENT position EMPTY>
<!ELEMENT lookat EMPTY>
<!ELEMENT up EMPTY>
<!ELEMENT horizontal_fov EMPTY>
<!ELEMENT resolution EMPTY>
<!ELEMENT max_bounces EMPTY>

<!ELEMENT lights ((ambient_light | point_light | parallel_light | spot_light)*)>
<!ELEMENT ambient_light (color)>
<!ELEMENT point_light (color, position)>
<!ELEMENT parallel_light (color, direction)>
<!ELEMENT spot_light (color, position, direction, falloff)>
<!ELEMENT color EMPTY>
<!ELEMENT direction EMPTY>
<!ELEMENT falloff EMPTY>

<!ELEMENT surfaces ((sphere | mesh)*)>
<!ELEMENT sphere (position, (material_solid | material_textured), transform?)>
<!ELEMENT mesh ((material_solid | material_textured), transform?)>

<!ELEMENT material_solid (color, phong, reflectance, transmittance, refraction)>
<!ELEMENT material_textured (texture, phong, reflectance, transmittance, refraction)>
<!ELEMENT phong EMPTY>
<!ELEMENT reflectance EMPTY>
<!ELEMENT transmittance EMPTY>
<!ELEMENT refraction EMPTY>
<!ELEMENT texture EMPTY>

<!ELEMENT transform ((translate | scale | rotateX | rotateY | rotateZ)*)>
<!ELEMENT translate EMPTY>
<!ELEMENT scale EMPTY>
<!ELEMENT rotateX EMPTY>
<!ELEMENT rotateY EMPTY>
<!ELEMENT rotateZ EMPTY>



<!ATTLIST scene output_file CDATA #REQUIRED>

<!ATTLIST background_color
	r NMTOKEN #REQUIRED
	g NMTOKEN #REQUIRED
	b NMTOKEN #REQUIRED>

<!ATTLIST position
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>

<!ATTLIST lookat
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>	

<!ATTLIST up
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>

<!ATTLIST horizontal_fov
	angle NMTOKEN #REQUIRED>

<!ATTLIST resolution
	horizontal NMTOKEN #REQUIRED
	vertical NMTOKEN #REQUIRED>

<!ATTLIST max_bounces
	n NMTOKEN #REQUIRED>

<!ATTLIST color
	r NMTOKEN #REQUIRED
	g NMTOKEN #REQUIRED
	b NMTOKEN #REQUIRED>

<!ATTLIST direction
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>

<!ATTLIST falloff
	alpha1 NMTOKEN #REQUIRED
	alpha2 NMTOKEN #REQUIRED>

<!ATTLIST sphere
	radius NMTOKEN #REQUIRED>

<!ATTLIST mesh
	name CDATA #REQUIRED>

<!ATTLIST phong
	ka NMTOKEN #REQUIRED
	kd NMTOKEN #REQUIRED
	ks NMTOKEN #REQUIRED
	exponent NMTOKEN #REQUIRED>

<!ATTLIST reflectance
	r NMTOKEN #REQUIRED>

<!ATTLIST transmittance
	t NMTOKEN #REQUIRED>

<!ATTLIST refraction
	iof NMTOKEN #REQUIRED>

<!ATTLIST texture
	name CDATA #REQUIRED>

<!ATTLIST translate
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>

<!ATTLIST scale
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>

<!ATTLIST rotateX
	theta NMTOKEN #REQUIRED>

<!ATTLIST rotateY
	theta NMTOKEN #REQUIRED>

<!ATTLIST rotateZ
	theta NMTOKEN #REQUIRED>

=== Rouji/raymond/scenes/dtd-test.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene output_file="myImage.png">
	<background_color r="255" g="0" b="0"/>
	<camera>
		<position x="1.0" y="-2.0E-10" z="-3"/>
		<lookat x="1" y="2" z="3"/>
		<up x="1" y="2" z="3"/>
		<horizontal_fov angle="90"/>
		<resolution horizontal="1920" vertical="1080"/>
		<max_bounces n="100"/>
	</camera>
	<lights>
		<ambient_light>
			<color r="1" g="2" b="3"/>
		</ambient_light>
		<point_light>
			<color r="1" g="2" b="3"/>
			<position x="1" y="2" z="3"/>
		</point_light>
		<parallel_light>
			<color r="1" g="2" b="3"/>
			<direction x="1" y="2" z="3"/>
		</parallel_light>
		<spot_light>
			<color r="1" g="2" b="3"/>
			<position x="1" y="2" z="3"/>
			<direction x="1" y="2" z="3"/>
			<falloff alpha1="1" alpha2="3"/>
		</spot_light>
	</lights>
	<surfaces>
		<sphere radius="123">
			<position x="1" y="2" z="3"/>
			<material_solid>
				<color r="1" g="2" b="3"/>
				<phong ka="1" kd="1" ks="1" exponent="1"/>
				<reflectance r="1"/>
				<transmittance t="1"/>
				<refraction iof="1"/>
			</material_solid>
			<transform>
				<translate x="1" y="1" z="1"/>
				<scale x="1" y="1" z="1"/>
				<rotateX theta="1"/>
				<rotateY theta="1"/>
				<rotateZ theta="1"/>
			</transform>
		</sphere>
		<mesh name="duck.dae">
			<material_textured>
				<texture name=""/>
				<phong ka="1" kd="1" ks="1" exponent="1"/>
				<reflectance r="1"/>
				<transmittance t="1"/>
				<refraction iof="1"/>
			</material_textured>
			<transform>
				<translate x="1" y="1" z="1"/>
				<scale x="1" y="1" z="1"/>
				<rotateX theta="1"/>
				<rotateY theta="1"/>
				<rotateZ theta="1"/>
				<translate x="1" y="1" z="1"/>
				<scale x="1" y="1" z="1"/>
			</transform>
		</mesh>
	</surfaces>
</scene>
